### ISSUE TITLE
Blackstone Stoves are placed with normal fire 

### ISSUE THREAD

**Issue by thelegitdolt** [SoyTutta/MyNethersDelight#17]
<img width="1512" alt="Screenshot 2024-06-10 at 3 44 14 PM" src="https://github.com/SoyTutta/MyNethersDelight/assets/50085439/1f861f7c-098c-4f60-b7ca-541a6feb2c7a">
However the recipe still requires a soul campfire

**Comment by kentapainter** [comment]
@thelegitdolt Yes, the same thing happened to me. It's strange that using a soul campfire doesn't end up with soul fire, but let me tell you the recipe if it helps while they update that; take the nether stove and an item of any type of nether souls, it can be sand or soil or compost or you know already, and place them both on a crafting table.

Really odd, but we just have to wait for the dev to read this issue.

**Comment by SoyTutta** [comment]
There are several recipes for making the stove nether. You are probably using the one that overrides the campfire
this is an intentional feature

try interact with those objects in your hand in the nether stove, it will still transform into its soul/fire state.
if this gets too confusing I can remove it-
